local new_set = MiniTest.new_set
local expect = MiniTest.expect
local H = dofile("tests/helpers.lua")
local T = new_set()

local ensure = require("config.markdown.config_ensure")

T["config_ensure"] = new_set()

T["config_ensure"]["write_marksman creates valid TOML"] = function()
  H.with_temp_dir(function(dir)
    local path = dir .. "/.marksman.toml"
    ensure._write_marksman(path)
    local content = table.concat(vim.fn.readfile(path), "\n")
    -- Check key content markers
    expect.equality(content:find("Generated by MarkdownEnsureConfigs") ~= nil, true)
    expect.equality(content:find("%[core%]") ~= nil, true)
    expect.equality(content:find("%[completion%]") ~= nil, true)
  end)
end

T["config_ensure"]["write_marksman creates parent dirs"] = function()
  H.with_temp_dir(function(dir)
    local path = dir .. "/sub/deep/.marksman.toml"
    ensure._write_marksman(path)
    expect.equality(vim.fn.filereadable(path), 1)
  end)
end

T["config_ensure"]["write_remark creates valid JSON with hub-absolute plugins"] = function()
  H.with_temp_dir(function(dir)
    local path = dir .. "/.remarkrc.json"
    ensure._write_remark(path)
    local content = table.concat(vim.fn.readfile(path), "\n")
    local ok, rc = pcall(vim.json.decode, content)
    expect.equality(ok, true)
    expect.equality(rc.settings.bullet, "-")
    -- Plugins must be absolute paths into the shared hub: bare names
    -- only resolve when the project has its own node_modules, and a
    -- broken rcfile silently kills remark for everything below it.
    local hub = require("config.remark_auto").CENTRAL_PKGS
    expect.equality(#rc.plugins > 0, true)
    for _, p in ipairs(rc.plugins) do
      expect.equality(vim.startswith(p, hub .. "/"), true)
    end
  end)
end

T["config_ensure"]["write_remark creates parent dirs"] = function()
  H.with_temp_dir(function(dir)
    local path = dir .. "/sub/deep/.remarkrc.json"
    ensure._write_remark(path)
    expect.equality(vim.fn.filereadable(path), 1)
  end)
end

return T
