-- after/ftplugin/markdown.lua
-- ------------------------------------------------------------
-- Markdown helpers: auto-create configs + fix roots for scratch buffers
-- Commands:
--   :MarksmanEnsureConfig[!]  -> create .marksman.toml if missing (use ! to open)
--   :RemarkEnsureConfig[!]    -> create .remarkrc.mjs if missing (use ! to open)
--   :MarkdownEnsureConfigs[!] -> create both (use ! to open them)
-- Behavior:
--   * On first save of a scratch Markdown buffer, restart marksman/remark_ls
--     so they re-root to the correct project.
--   * On save, if no configs exist at project root, create them.
-- ------------------------------------------------------------
if vim.g._markdown_config_helper then
  return
end
vim.g._markdown_config_helper = true

-- ---------- root discovery (no deprecated APIs) ----------
local function project_root(start)
  local cfgdir = vim.fn.stdpath("config")
  start = (type(start) == "string" and #start > 0) and start
    or vim.api.nvim_buf_get_name(0)
  if start == "" then
    start = vim.fn.getcwd()
  end

  local hit = vim.fs.find({
    ".git",
    ".marksman.toml",
    "marksman.toml",
    ".remarkrc.mjs",
    ".remarkrc.js",
    ".remarkrc.cjs",
    ".remarkrc",
    ".remarkrc.json",
    ".remarkrc.yaml",
    ".remarkrc.yml",
    "remark.config.mjs",
    "remark.config.js",
    "remark.config.cjs",
  }, { path = start, upward = true })[1]

  local root = hit and vim.fs.dirname(hit) or vim.fs.dirname(start)
  -- avoid accidentally rooting to your Neovim config dir
  if not start:find(cfgdir, 1, true) and root:find(cfgdir, 1, true) then
    root = vim.fs.dirname(start)
  end
  return root
end

local function find_marksman_config(root)
  for _, name in ipairs({ ".marksman.toml", "marksman.toml" }) do
    local p = root .. "/" .. name
    if vim.fn.filereadable(p) == 1 then
      return p
    end
  end
end

local function find_remark_config(root)
  for _, name in ipairs({
    ".remarkrc.mjs",
    ".remarkrc.js",
    ".remarkrc.cjs",
    ".remarkrc",
    ".remarkrc.json",
    ".remarkrc.yaml",
    ".remarkrc.yml",
    "remark.config.mjs",
    "remark.config.js",
    "remark.config.cjs",
  }) do
    local p = root .. "/" .. name
    if vim.fn.filereadable(p) == 1 then
      return p
    end
  end
end

local function ensure_dir(filepath)
  local dir = vim.fs.dirname(filepath)
  if vim.fn.isdirectory(dir) == 0 then
    pcall(vim.fn.mkdir, dir, "p")
  end
end

-- ---------- writers ----------
local function write_marksman(path)
  ensure_dir(path)
  local lines = {
    "# Generated by MarkdownEnsureConfigs",
    "",
    "[core]",
    "title_from_heading = false",
    "",
    "[code_action]",
    "toc.enable = false",
    "create_missing_file.enable = true",
    "",
    "[completion]",
    'wiki.style = "file-stem"',
    "",
    "[markdown]",
    'file_extensions = ["md", "markdown"]',
    "glfm_heading_ids.enable = true",
    "",
  }
  vim.fn.writefile(lines, path)
end

local function write_remark(path)
  ensure_dir(path)
  local lines = {
    "// Generated by MarkdownEnsureConfigs",
    "// If imports fail, run in project root:",
    "//   npm i -D remark-gfm remark-frontmatter remark-preset-lint-recommended",
    "",
    'import remarkGfm from "remark-gfm";',
    'import remarkFrontmatter from "remark-frontmatter";',
    'import remarkPresetLintRecommended from "remark-preset-lint-recommended";',
    "",
    "export default {",
    "  settings: {",
    '    bullet: "-",',
    '    listItemIndent: "one",',
    "    fences: true,",
    "  },",
    "  plugins: [remarkGfm, remarkFrontmatter, remarkPresetLintRecommended],",
    "};",
    "",
  }
  vim.fn.writefile(lines, path)
end

local function ensure_marksman(open_after)
  local root = project_root()
  local existing = find_marksman_config(root)
  if existing then
    if open_after then
      vim.cmd.edit(vim.fn.fnameescape(existing))
    end
    return existing
  end
  local path = root .. "/.marksman.toml"
  write_marksman(path)
  if open_after then
    vim.cmd.edit(vim.fn.fnameescape(path))
  end
  return path
end

local function ensure_remark(open_after)
  local root = project_root()
  local existing = find_remark_config(root)
  if existing then
    if open_after then
      vim.cmd.edit(vim.fn.fnameescape(existing))
    end
    return existing
  end
  local path = root .. "/.remarkrc.mjs"
  write_remark(path)
  if open_after then
    vim.cmd.edit(vim.fn.fnameescape(path))
  end
  return path
end

-- ---------- user commands ----------
vim.api.nvim_create_user_command(
  "MarksmanEnsureConfig",
  function(args)
    ensure_marksman(args.bang)
  end,
  { bang = true, desc = "Create .marksman.toml if missing (use ! to open it)" }
)

vim.api.nvim_create_user_command(
  "RemarkEnsureConfig",
  function(args)
    ensure_remark(args.bang)
  end,
  { bang = true, desc = "Create .remarkrc.mjs if missing (use ! to open it)" }
)

vim.api.nvim_create_user_command("MarkdownEnsureConfigs", function(args)
  ensure_marksman(false)
  ensure_remark(false)
  if args.bang then
    local root = project_root()
    for _, fname in ipairs({ ".marksman.toml", ".remarkrc.mjs" }) do
      local p = root .. "/" .. fname
      if vim.fn.filereadable(p) == 1 then
        vim.cmd.split(vim.fn.fnameescape(p))
      end
    end
  end
end, {
  bang = true,
  desc = "Create both Markdown configs if missing (use ! to open)",
})

-- ---------- auto-restart + auto-create on save ----------
local aug =
  vim.api.nvim_create_augroup("MarkdownRootAndConfigs", { clear = true })

-- mark scratch markdown buffers so we know to restart after first save
vim.api.nvim_create_autocmd({ "BufEnter", "BufNewFile" }, {
  group = aug,
  pattern = "*.md,*.markdown,*.mdx",
  callback = function(args)
    if vim.api.nvim_buf_get_name(args.buf) == "" then
      vim.b[args.buf]._md_was_scratch = true
    end
  end,
})

-- on save: ensure configs; if it was scratch, restart LSPs for this buffer
vim.api.nvim_create_autocmd("BufWritePost", {
  group = aug,
  pattern = { "*.md", "*.markdown", "*.mdx" },
  callback = function(args)
    -- 1) auto-create configs at project root if missing
    ensure_marksman(false)
    ensure_remark(false)

    -- 2) if this buffer started life as scratch, restart its markdown LSPs
    if vim.b[args.buf]._md_was_scratch then
      vim.b[args.buf]._md_was_scratch = nil

      -- Neovim 0.12+: use get_clients()
      local clients = vim.lsp.get_clients({ bufnr = args.buf })
      local to_restart = {}
      for _, c in ipairs(clients) do
        if c.name == "marksman" or c.name == "remark_ls" then
          table.insert(to_restart, c.name)
          if type(c.stop) == "function" then
            -- 0.12 signature: no args
            pcall(c.stop, c)
          else
            -- fallback for older versions
            pcall(vim.lsp.stop_client, c.id, true)
          end
        end
      end

      -- Give the old client a moment to exit, then re-add for this buffer
      vim.defer_fn(function()
        local ok, lsp = pcall(require, "lspconfig")
        if not ok then
          return
        end
        for _, name in ipairs(to_restart) do
          local cfg = lsp[name]
          if cfg and cfg.manager then
            cfg.manager.try_add(args.buf)
          end
        end
      end, 100)
    end
  end,
})
