-- after/ftplugin/markdown.lua

vim.api.nvim_create_autocmd("BufReadPost", {
  pattern = "*.md",
  callback = function()
    -- only run if not triggered already
    if vim.b.peek_triggered then
      return
    end

    local text =
      table.concat(vim.api.nvim_buf_get_lines(0, 0, -1, false), "\n")
    local has_latex = text:match("\\%(")
      or text:match("\\%[")
      or text:match("%$%$[^%$]+%$%$")
      or text:match("%$[^%$]+%$")

    if has_latex then
      vim.b.peek_triggered = true
      pcall(vim.cmd, "Markview Stop") -- suppress error if Markview isn't loaded
      -- CALL PEEK VIA LUA API:
      if pcall(require, "peek") then
        require("peek").open()
      end
    end
    -- Markview is intentionally NOT auto-started; use :Markview to enable manually.
  end,
})

-- ------------------------------------------------------------
-- Markdown helpers: auto-create configs + fix roots for scratch buffers
-- Commands:
--   :MarksmanEnsureConfig[!]  -> create .marksman.toml if missing (use ! to open)
--   :RemarkEnsureConfig[!]    -> create .remarkrc.mjs if missing (use ! to open)
--   :MarkdownEnsureConfigs[!] -> create both (use ! to open them)
-- Behavior:
--   * On first save of a scratch Markdown buffer, restart marksman/remark_ls
--     so they re-root to the correct project.
--   * On save, if no configs exist at project root, create them.
-- ------------------------------------------------------------
if vim.g._markdown_config_helper then
  return
end
vim.g._markdown_config_helper = true

-- ---------- root discovery ----------
local roots = require("config.roots")

local function project_root(start)
  return roots.find(start, roots.all_markers) or vim.fs.dirname(
    (type(start) == "string" and #start > 0) and start
      or vim.api.nvim_buf_get_name(0)
  )
end

local find_marksman_config = roots.find_marksman_config
local find_remark_config = roots.find_remark_config

local function ensure_dir(filepath)
  local dir = vim.fs.dirname(filepath)
  if vim.fn.isdirectory(dir) == 0 then
    pcall(vim.fn.mkdir, dir, "p")
  end
end

-- ---------- writers ----------
local function write_marksman(path)
  ensure_dir(path)
  local lines = {
    "# Generated by MarkdownEnsureConfigs",
    "",
    "[core]",
    "title_from_heading = false",
    "",
    "[code_action]",
    "toc.enable = false",
    "create_missing_file.enable = true",
    "",
    "[completion]",
    'wiki.style = "file-stem"',
    "",
    "[markdown]",
    'file_extensions = ["md", "markdown"]',
    "glfm_heading_ids.enable = true",
    "",
  }
  vim.fn.writefile(lines, path)
end

local function write_remark(path)
  ensure_dir(path)
  local lines = {
    "// Generated by MarkdownEnsureConfigs",
    "// If imports fail, run in project root:",
    "//   npm i -D remark-gfm remark-frontmatter remark-preset-lint-recommended",
    "",
    'import remarkGfm from "remark-gfm";',
    'import remarkFrontmatter from "remark-frontmatter";',
    'import remarkPresetLintRecommended from "remark-preset-lint-recommended";',
    "",
    "export default {",
    "  settings: {",
    '    bullet: "-",',
    '    listItemIndent: "one",',
    "    fences: true,",
    "  },",
    "  plugins: [remarkGfm, remarkFrontmatter, remarkPresetLintRecommended],",
    "};",
    "",
  }
  vim.fn.writefile(lines, path)
end

local function ensure_marksman(open_after)
  local root = project_root()
  local existing = find_marksman_config(root)
  if existing then
    if open_after then
      vim.cmd.edit(vim.fn.fnameescape(existing))
    end
    return existing
  end
  local path = root .. "/.marksman.toml"
  write_marksman(path)
  if open_after then
    vim.cmd.edit(vim.fn.fnameescape(path))
  end
  return path
end

local function ensure_remark(open_after)
  local root = project_root()
  local existing = find_remark_config(root)
  if existing then
    if open_after then
      vim.cmd.edit(vim.fn.fnameescape(existing))
    end
    return existing
  end
  local path = root .. "/.remarkrc.mjs"
  write_remark(path)
  if open_after then
    vim.cmd.edit(vim.fn.fnameescape(path))
  end
  return path
end

-- ---------- user commands ----------
vim.api.nvim_create_user_command(
  "MarksmanEnsureConfig",
  function(args)
    ensure_marksman(args.bang)
  end,
  { bang = true, desc = "Create .marksman.toml if missing (use ! to open it)" }
)

vim.api.nvim_create_user_command(
  "RemarkEnsureConfig",
  function(args)
    ensure_remark(args.bang)
  end,
  { bang = true, desc = "Create .remarkrc.mjs if missing (use ! to open it)" }
)

vim.api.nvim_create_user_command("MarkdownEnsureConfigs", function(args)
  ensure_marksman(false)
  ensure_remark(false)
  if args.bang then
    local root = project_root()
    for _, fname in ipairs({ ".marksman.toml", ".remarkrc.mjs" }) do
      local p = root .. "/" .. fname
      if vim.fn.filereadable(p) == 1 then
        vim.cmd.split(vim.fn.fnameescape(p))
      end
    end
  end
end, {
  bang = true,
  desc = "Create both Markdown configs if missing (use ! to open)",
})

-- ---------- auto-restart + auto-create on save ----------
local aug =
  vim.api.nvim_create_augroup("MarkdownRootAndConfigs", { clear = true })

-- mark scratch markdown buffers so we know to restart after first save
vim.api.nvim_create_autocmd({ "BufEnter", "BufNewFile" }, {
  group = aug,
  pattern = "*.md,*.markdown,*.mdx",
  callback = function(args)
    if vim.api.nvim_buf_get_name(args.buf) == "" then
      vim.b[args.buf]._md_was_scratch = true
    end
  end,
})

-- on save: ensure configs; if it was scratch, restart LSPs for this buffer
vim.api.nvim_create_autocmd("BufWritePost", {
  group = aug,
  pattern = { "*.md", "*.markdown", "*.mdx" },
  callback = function(args)
    -- 1) auto-create configs at project root if missing
    ensure_marksman(false)
    ensure_remark(false)

    -- 2) if this buffer started life as scratch, restart its markdown LSPs
    if vim.b[args.buf]._md_was_scratch then
      vim.b[args.buf]._md_was_scratch = nil

      -- Neovim 0.12+: use get_clients()
      local clients = vim.lsp.get_clients({ bufnr = args.buf })
      local to_restart = {}
      for _, c in ipairs(clients) do
        if c.name == "marksman" or c.name == "remark_ls" then
          table.insert(to_restart, c.name)
          pcall(c.stop, c)
        end
      end

      -- Give the old client a moment to exit, then re-add for this buffer
      vim.defer_fn(function()
        local ok, lsp = pcall(require, "lspconfig")
        if not ok then
          return
        end
        for _, name in ipairs(to_restart) do
          local cfg = lsp[name]
          if cfg and cfg.manager then
            cfg.manager.try_add(args.buf)
          end
        end
      end, 100)
    end
  end,
})

-- Convert \(..\), \[..] math delimiters to $..$, $$..$$ using pandoc.
-- Robust because pandoc parses Markdown structure (won't touch code spans/blocks as math).

local function math_delims_to_dollars()
  local buf = vim.api.nvim_get_current_buf()
  local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
  local input = table.concat(lines, "\n")

  -- Prefer LF to avoid accidental CRLF churn in-buffer (optional)
  -- You can remove --eol=lf if you want OS-native behavior.
  local cmd = {
    "pandoc",
    "--from=markdown+tex_math_single_backslash",
    "--to=markdown+tex_math_dollars",
    "--wrap=preserve",
    "--eol=lf",
  }

  -- vim.fn.systemlist is widely available and easy for “run command, capture output”.
  -- It runs {cmd} and returns stdout as a List of lines.  :contentReference[oaicite:4]{index=4}
  local out = vim.fn.systemlist(cmd, input)
  local code = vim.v.shell_error

  if code ~= 0 then
    vim.notify(
      ("pandoc failed (exit %d). Is pandoc installed and on $PATH?"):format(
        code
      ),
      vim.log.levels.ERROR
    )
    return
  end

  -- Replace buffer contents
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, out)
  vim.notify(
    "Converted \\(\\)/\\[\\] math delimiters to $/$$ via pandoc.",
    vim.log.levels.INFO
  )
end

vim.api.nvim_create_user_command(
  "MathDelimsToDollars",
  math_delims_to_dollars,
  {
    desc = "Convert \\(\\)/\\[\\] math delimiters to $/$$ using pandoc",
  }
)

-- Export current markdown buffer to HTML via pandoc
vim.api.nvim_create_user_command("ExportHTML", function(opts)
  local file = vim.api.nvim_buf_get_name(0)
  if file == "" then
    vim.notify(
      "No file found — save buffer before exporting",
      vim.log.levels.ERROR
    )
    return
  end

  -- Change extension .md → .html
  local output = file:gsub("%.%w+$", ".html")

  -- Build pandoc command
  local cmd = {
    "pandoc",
    "-s", -- standalone HTML
    "--from=markdown+tex_math_single_backslash",
    "--to=html5",
    "--mathjax", -- math rendering in browser
    "-o",
    output,
    file,
  }

  -- Execute Pandoc
  local result = vim.fn.system(cmd)
  local code = vim.v.shell_error
  if code == 0 then
    vim.notify("Exported HTML ➤ " .. output, vim.log.levels.INFO)
  else
    vim.notify("pandoc failed: " .. result, vim.log.levels.ERROR)
  end
end, {
  desc = "Export current markdown to HTML with math via pandoc",
})

-- ── mathdelim.py integration ──────────────────────────────────────────────────
-- Commands (only available in markdown buffers):
--   :DelimToggle      – auto-detect dominant style and convert to the other
--   :DelimDollars     – convert \(…\) / \[…\] → $…$ / $$…$$
--   :DelimParens      – convert $…$ / $$…$$ → \(…\) / \[…\]
--   :ExportToGippity  – copy buffer (as LaTeX delimiters) to clipboard; no buffer change
-- Auto-save: \( / \[ delimiters are silently converted → $ on every BufWritePre.
-- ─────────────────────────────────────────────────────────────────────────────

--- Run `mathdelim.py [args…]` on *buf* (default: current buffer) in-place.
--- Returns true on success, false on failure (with a notification).
local function run_mathdelim(args, buf)
  buf = buf or vim.api.nvim_get_current_buf()
  local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
  local input = table.concat(lines, "\n")
  local cmd = vim.list_extend({ "mathdelim.py" }, args or {})
  local out = vim.fn.systemlist(cmd, input)
  if vim.v.shell_error ~= 0 then
    local hint = (#args == 0) and "; use :DelimDollars or :DelimParens" or ""
    vim.notify(
      ("mathdelim: conversion failed (exit %d)%s"):format(vim.v.shell_error, hint),
      vim.log.levels.WARN
    )
    return false
  end
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, out)
  return true
end

vim.api.nvim_create_user_command("DelimToggle", function()
  if run_mathdelim({}) then
    vim.notify("Math delimiters toggled.", vim.log.levels.INFO)
  end
end, {
  desc = "Auto-detect dominant delimiter style and toggle to the other",
})

vim.api.nvim_create_user_command("DelimDollars", function()
  if run_mathdelim({ "--to-dollar" }) then
    vim.notify("Converted math delimiters → $…$ / $$…$$", vim.log.levels.INFO)
  end
end, {
  desc = "Convert math delimiters to dollar style ($…$ / $$…$$)",
})

vim.api.nvim_create_user_command("DelimParens", function()
  if run_mathdelim({ "--to-latex" }) then
    vim.notify("Converted math delimiters → \\(…\\) / \\[…\\]", vim.log.levels.INFO)
  end
end, {
  desc = "Convert math delimiters to LaTeX style (\\(…\\) / \\[…\\])",
})

-- On every save: silently convert any LaTeX-style delimiters to dollars so
-- that markdown preview plugins (which only support $…$) render correctly.
-- The check for \( / \[ means already-dollar documents are never touched.
local _math_aug =
  vim.api.nvim_create_augroup("MarkdownMathDelims", { clear = true })

vim.api.nvim_create_autocmd("BufWritePre", {
  group = _math_aug,
  pattern = { "*.md", "*.markdown", "*.mdx" },
  callback = function(ev)
    local lines = vim.api.nvim_buf_get_lines(ev.buf, 0, -1, false)
    local text = table.concat(lines, "\n")
    -- Quick bail-out: nothing to do if no LaTeX-style delimiters present
    if not (text:find("\\%(") or text:find("\\%[")) then
      return
    end
    local out = vim.fn.systemlist({ "mathdelim.py", "--to-dollar" }, text)
    if vim.v.shell_error == 0 then
      vim.api.nvim_buf_set_lines(ev.buf, 0, -1, false, out)
    end
  end,
})

-- ExportToGippity: read buffer, convert to LaTeX delimiters, place result in
-- the unnamed register (") and the system clipboard (+).  Buffer is untouched.
vim.api.nvim_create_user_command("ExportToGippity", function()
  local buf = vim.api.nvim_get_current_buf()
  local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
  local input = table.concat(lines, "\n")

  local out = vim.fn.systemlist({ "mathdelim.py", "--to-latex" }, input)
  if vim.v.shell_error ~= 0 then
    vim.notify(
      ("ExportToGippity: mathdelim.py failed (exit %d)"):format(vim.v.shell_error),
      vim.log.levels.ERROR
    )
    return
  end

  local result = table.concat(out, "\n")
  vim.fn.setreg('"', result) -- unnamed / default yank register
  vim.fn.setreg("+", result) -- system clipboard
  vim.notify(
    ("Converted to LaTeX delimiters and copied to clipboard (%d lines)."):format(#out),
    vim.log.levels.INFO
  )
end, {
  desc = "Copy buffer as LaTeX-style math to clipboard (buffer unchanged)",
})
